
spring:
  application:
    name: JwtAuthentication

  datasource:
    url: ${POSTGRES_HOST}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jackson:
    locale: ru_RU
  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:/db.changelog/db.changelog-master.yaml
    default-schema: public
logging:
  level:
    liquibase: DEBUG
    org:
      springframework:
        security: DEBUG


server:
  ssl:
    key-alias: certificate
    key-store: classpath:/certificates/keystore.jks
    key-store-type: JKS
    key-password: 123456
  port: 8081

jwt:
   secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
   lifetime: 10m